---
# Project Information
site_name: Cookiecutter PyPackage
site_author: Marco Gancitano
site_description: >-
    Cookiecutter to create a Python package. Powered by Poetry,
    GitHub actions, and MkDocs-Material.

# Repository information
repo_name: mgancita/cookiecutter-pypackage
repo_url: https://github.com/mgancita/cookiecutter-pypackage
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2020 Marco Gancitano

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mgancita
      name: mgancita on GitHub
    - icon: fontawesome/brands/kaggle
      link: https://kaggle.com/mgancita
      name: mgancita on Kaggle

# Page tree
nav:
  - Home:
    - Introduction: index.md
  - Getting started:
    - Create local project: getting-started/create_local_project.md
    - Connect to remote repository: getting-started/connect_to_remote_repo.md
    - Configure GitHub repository: getting-started/configure_github_repo.md
    - Publish to test PyPI: getting-started/publish_to_test_pypi.md
    - Publish to PyPI: getting-started/publish_to_pypi.md
  - Advanced:
    - Feature explanation: advanced/feature_explanation.md
