---
name: Code Quality Checks

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Unit & Coverage test with pytest
      - name: Check yaml style with yamllint
        run: poetry run yamllint . -c yamllint-config.yaml
